licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ternary",
    hdrs = [
        "ternary.h",
    ],
    deps = [
        "//larq_compute_engine/core:types",
        "@org_tensorflow//tensorflow/lite:builtin_op_data",
    ],
)
